# Generated by Django 4.2.3 on 2025-06-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('narratives', '0069_rename_author_claim_submitter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_name', models.CharField(max_length=100)),
                ('integration_config', models.JSONField(blank=True, default=dict)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='narratives.source')),
            ],
        ),
    ]
