# Generated by Django 4.2.3 on 2024-02-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0003_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='description',
        ),
        migrations.RemoveField(
            model_name='action',
            name='slug',
        ),
        migrations.AddField(
            model_name='action',
            name='noun',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
