# Generated by Django 4.2.3 on 2024-02-28 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0004_remove_action_description_remove_action_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='narratives.action'),
        ),
    ]
