# Generated by Django 4.2.3 on 2024-02-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0006_tense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actors',
            name='description',
        ),
    ]
