# Generated by Django 4.2.3 on 2024-02-28 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0007_remove_actors_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='tense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='narratives.tense'),
        ),
    ]
