# Generated by Django 4.2.3 on 2024-02-28 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0008_narrative_tense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
        migrations.AddField(
            model_name='narrative',
            name='object_actor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_in_narratives', to='narratives.actor'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='object_identity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_in_narratives', to='narratives.identity'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='subject_actor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_in_narratives', to='narratives.actor'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='subject_identity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_in_narratives', to='narratives.identity'),
        ),
    ]
