# Generated by Django 4.2.3 on 2024-03-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0010_alter_narrative_object_actor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narrative',
            name='object_actor',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='object_identity',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='subject_actor',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='subject_identity',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='tense',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Tense',
        ),
    ]
