# Generated by Django 4.2.3 on 2024-03-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0011_remove_narrative_object_actor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='noun',
        ),
        migrations.AddField(
            model_name='action',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
