# Generated by Django 4.2.3 on 2024-04-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0012_remove_action_noun_action_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_choice', models.CharField(choices=[('past', 'Past'), ('present', 'Present'), ('future', 'Future')], default='past', max_length=32)),
                ('end_time_choice', models.CharField(choices=[('past', 'Past'), ('present', 'Present'), ('future', 'Future')], default='future', max_length=32)),
            ],
        ),
    ]
