# Generated by Django 4.2.3 on 2024-04-15 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0013_actiontime'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='narratives.actiontime'),
        ),
    ]
