# Generated by Django 4.2.3 on 2024-05-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0014_action_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narrative',
            name='action',
        ),
        migrations.AddField(
            model_name='action',
            name='noun_form',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='narrative',
            name='obj_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_action', to='narratives.action'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='obj_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_identity', to='narratives.identity'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='subj_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subj_action', to='narratives.action'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='subj_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subj_identity', to='narratives.identity'),
        ),
    ]
