# Generated by Django 4.2.3 on 2024-05-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0015_remove_narrative_action_action_noun_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='time',
        ),
        migrations.AddField(
            model_name='narrative',
            name='obj_action_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_action_time', to='narratives.actiontime'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='subj_action_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subj_action_time', to='narratives.actiontime'),
        ),
    ]
