# Generated by Django 4.2.3 on 2024-05-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0016_remove_action_time_narrative_obj_action_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='verbs',
            field=models.ManyToManyField(blank=True, to='narratives.verb'),
        ),
    ]
