# Generated by Django 4.2.3 on 2024-05-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0017_verb_action_verbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='noun_form',
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
