# Generated by Django 4.2.3 on 2024-05-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0018_remove_action_noun_form_alter_action_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
