# Generated by Django 4.2.3 on 2024-05-14 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0019_action_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='antonym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antonym_of', to='narratives.action'),
        ),
    ]
