# Generated by Django 4.2.3 on 2024-05-14 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0020_action_antonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='antonym',
        ),
        migrations.CreateModel(
            name='ActionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action1', to='narratives.action')),
                ('action2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action2', to='narratives.action')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='narratives.relationtype')),
            ],
        ),
    ]
