# Generated by Django 4.2.3 on 2024-05-14 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0021_relationtype_remove_action_antonym_actionrelation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narrative',
            old_name='obj_identity',
            new_name='object',
        ),
        migrations.RenameField(
            model_name='narrative',
            old_name='subj_identity',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='obj_action',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='obj_action_time',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='subj_action',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='subj_action_time',
        ),
        migrations.AddField(
            model_name='narrative',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_of_narrative', to='narratives.action'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='narratives.actiontime'),
        ),
    ]
