# Generated by Django 4.2.3 on 2024-05-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0022_rename_obj_identity_narrative_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrative',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
