# Generated by Django 4.2.3 on 2024-05-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0023_alter_narrative_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narrative',
            name='name',
        ),
    ]
