# Generated by Django 4.2.3 on 2024-05-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0024_remove_narrative_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrative',
            name='slug',
            field=models.SlugField(blank=True, max_length=1024, unique=True),
        ),
    ]
