# Generated by Django 4.2.3 on 2024-05-14 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0025_alter_narrative_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='object_narrative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obj_narrative', to='narratives.narrative'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='subject_narrative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subj_narrative', to='narratives.narrative'),
        ),
    ]
