# Generated by Django 4.2.3 on 2024-05-14 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0026_narrative_object_narrative_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narrative',
            old_name='object',
            new_name='object_identity',
        ),
        migrations.RenameField(
            model_name='narrative',
            old_name='subject',
            new_name='subject_identity',
        ),
    ]
