# Generated by Django 4.2.3 on 2024-05-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0027_rename_object_narrative_object_identity_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actionrelation',
            constraint=models.UniqueConstraint(fields=('action1', 'action2', 'relation'), name='unique_action_relation'),
        ),
    ]
