# Generated by Django 4.2.3 on 2024-09-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0030_modality_narrative_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrative',
            name='modality_negated',
            field=models.BooleanField(default=False),
        ),
    ]
