# Generated by Django 4.2.3 on 2024-09-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0032_remove_narrative_object_identity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Identity',
            new_name='Category',
        ),
    ]
