# Generated by Django 4.2.3 on 2024-09-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0036_category_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='epoch',
            unique_together={('category', 'start_date', 'end_date')},
        ),
    ]
