# Generated by Django 4.2.3 on 2024-11-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0037_alter_category_name_alter_epoch_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='values',
            field=models.ManyToManyField(blank=True, related_name='categories', to='narratives.value'),
        ),
        migrations.AddField(
            model_name='narrative',
            name='values',
            field=models.ManyToManyField(blank=True, related_name='narratives', to='narratives.value'),
        ),
    ]
