# Generated by Django 4.2.3 on 2024-12-10 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0038_value_category_values_narrative_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolOfThoughtType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolOfThought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('parent_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_schools', to='narratives.schoolofthought')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools_of_thought', to='narratives.schoolofthoughttype')),
            ],
        ),
    ]
