# Generated by Django 4.2.3 on 2024-12-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0039_schoolofthoughttype_schoolofthought'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('unverified', 'Unverified'), ('pending_ai_review', 'Pending AI Review'), ('ai_reviewed', 'AI Reviewed'), ('user_approved', 'User Approved'), ('validator_review', 'Validator Review'), ('approved_for_blockchain', 'Approved for Blockchain'), ('published', 'Published'), ('rejected', 'Rejected')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the verification status.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
