# Generated by Django 4.2.3 on 2024-12-19 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0040_verificationstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The text of the claim submitted by the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_status', models.ForeignKey(help_text='The current verification status of the claim.', on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='narratives.verificationstatus')),
            ],
        ),
    ]
