# Generated by Django 4.2.3 on 2025-01-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0041_claim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='verificationstatus',
            options={'verbose_name': 'Verification Status', 'verbose_name_plural': 'Verification Statuses'},
        ),
        migrations.AddField(
            model_name='claim',
            name='status_description',
            field=models.TextField(blank=True, help_text='Description or reason for the current verification status.', null=True),
        ),
    ]
