# Generated by Django 4.2.3 on 2025-01-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0042_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='verification_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='narratives.verificationstatus'),
        ),
    ]
