# Generated by Django 4.2.3 on 2025-01-22 23:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0043_claim_slug_alter_claim_status_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(help_text='Solana wallet address', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Account creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('verification_status', models.ForeignKey(help_text='Verification status of the user', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='narratives.verificationstatus')),
            ],
        ),
    ]
