# Generated by Django 4.2.3 on 2025-01-27 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0044_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='author',
            field=models.CharField(default='3vpi8QbrDVcSpTtVEoajRPNqzAdBadD4CBrH93uHm9FY', help_text='Wallet address (for user claims) or AI model name (for AI-generated claims).', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='parent_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_variants', to='narratives.claim'),
        ),
    ]
