# Generated by Django 4.2.3 on 2025-01-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0045_claim_author_claim_parent_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationstatus',
            name='name',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending_ai_review', 'Pending AI Review'), ('ai_reviewed', 'AI Reviewed'), ('user_approved', 'User Approved'), ('ai_variants_generated', 'AI Variants Generated'), ('validator_review', 'Validator Review'), ('approved_for_blockchain', 'Approved for Blockchain'), ('published', 'Published'), ('rejected', 'Rejected')], max_length=50, unique=True),
        ),
    ]
