# Generated by Django 4.2.3 on 2025-01-30 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0046_alter_verificationstatus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(help_text='Wallet address of the market creator.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_address', models.CharField(blank=True, help_text='Future Smart Contract address.', max_length=255, null=True)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash.', max_length=255, null=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market', to='narratives.claim')),
            ],
        ),
    ]
