# Generated by Django 4.2.3 on 2025-01-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0047_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_model',
            field=models.CharField(blank=True, help_text='AI model used for refinement.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='generated_by_ai',
            field=models.BooleanField(default=False, help_text='Indicates if this claim was generated by AI.'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='author',
            field=models.CharField(help_text='Wallet address of the original user.', max_length=255),
        ),
        migrations.AlterField(
            model_name='claim',
            name='text',
            field=models.TextField(help_text='The text of the claim submitted by the user.', unique=True),
        ),
    ]
