# Generated by Django 4.2.3 on 2025-02-05 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0049_alter_verificationstatus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], max_length=5)),
                ('shares', models.FloatField(default=0.0)),
                ('cost_basis', models.FloatField(default=0.0)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='narratives.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='narratives.useraccount')),
            ],
        ),
    ]
