# Generated by Django 4.2.3 on 2025-02-05 23:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0050_marketposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='false_shares_remaining',
            field=models.DecimalField(decimal_places=8, default=Decimal('1000000000.0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='market',
            name='true_shares_remaining',
            field=models.DecimalField(decimal_places=8, default=Decimal('1000000000.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='marketposition',
            name='cost_basis',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='marketposition',
            name='shares',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20),
        ),
    ]
