# Generated by Django 4.2.3 on 2025-02-06 11:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0051_market_false_shares_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('1000.0'), help_text='Temporary wallet balance in SOL', max_digits=20),
        ),
        migrations.AddConstraint(
            model_name='marketposition',
            constraint=models.UniqueConstraint(fields=('user', 'market'), name='unique_user_market'),
        ),
    ]
