# Generated by Django 4.2.3 on 2025-02-06 11:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0052_useraccount_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('1000.0'), help_text="User's balance in SOL tokens", max_digits=20),
        ),
    ]
