# Generated by Django 4.2.3 on 2025-06-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0053_alter_useraccount_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionRelation',
        ),
    ]
