# Generated by Django 4.2.3 on 2025-06-14 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0054_delete_actionrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narrative',
            name='action',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='time',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='ActionTime',
        ),
        migrations.DeleteModel(
            name='Verb',
        ),
    ]
