# Generated by Django 4.2.3 on 2025-06-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0055_remove_narrative_action_remove_narrative_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narrative',
            name='modality',
        ),
        migrations.RemoveField(
            model_name='narrative',
            name='modality_negated',
        ),
        migrations.DeleteModel(
            name='Modality',
        ),
    ]
