# Generated by Django 4.2.3 on 2025-06-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0057_delete_prediction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Narrative',
        ),
    ]
