# Generated by Django 4.2.3 on 2025-06-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0058_delete_narrative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.DeleteModel(
            name='CategoryType',
        ),
    ]
