# Generated by Django 4.2.3 on 2025-06-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0059_remove_category_category_type_delete_categorytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epoch',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='epoch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='epoch',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='title',
            field=models.CharField(default='helle', help_text='E.g., Biden Presidency, Cold War, etc.', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='epoch',
            name='category',
        ),
    ]
