# Generated by Django 4.2.3 on 2025-06-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0060_alter_epoch_options_alter_epoch_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
