# Generated by Django 4.2.3 on 2025-06-14 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0061_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelationType',
        ),
    ]
