# Generated by Django 4.2.3 on 2025-06-14 22:19

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0062_delete_relationtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epoch',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterField(
            model_name='claim',
            name='ai_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='author',
            field=models.CharField(help_text='Wallet address or AI model', max_length=255),
        ),
        migrations.AlterField(
            model_name='claim',
            name='generated_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='text',
            field=models.TextField(help_text='The claim text.', unique=True),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='contract_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolofthought',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('1000.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='verificationstatus',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
