# Generated by Django 4.2.3 on 2025-06-14 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0063_alter_epoch_options_alter_claim_ai_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epoch',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterField(
            model_name='claim',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='claim',
            name='text',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='contract_address',
            field=models.CharField(blank=True, help_text='Future Smart Contract address.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='transaction_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolofthought',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=1000.0, help_text="User's balance in SOL tokens", max_digits=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Account creation timestamp'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='value',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
