# Generated by Django 4.2.3 on 2025-06-19 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0066_genre_source_rawtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtext',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rawtexts', to='narratives.person'),
        ),
    ]
