# Generated by Django 4.2.3 on 2025-06-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0067_alter_rawtext_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='content_fingerprint',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
