# Generated by Django 4.2.3 on 2025-06-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0068_claim_content_fingerprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='author',
            new_name='submitter',
        ),
        migrations.AddField(
            model_name='claim',
            name='attributed_persons',
            field=models.ManyToManyField(blank=True, related_name='associated_claims', to='narratives.person'),
        ),
    ]
