# Generated by Django 4.2.3 on 2025-06-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0069_rename_author_claim_submitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtext',
            name='subtitle',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='rawtext',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
