# Generated by Django 4.2.3 on 2025-06-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0070_alter_rawtext_subtitle_alter_rawtext_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtext',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
