# Generated by Django 4.2.3 on 2025-06-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0071_alter_rawtext_slug_alter_source_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Timezone of the source, e.g. America/New_York', max_length=50),
        ),
    ]
