# Generated by Django 4.2.3 on 2025-06-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0072_source_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtext',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original source URL for reference', null=True),
        ),
    ]
