# Generated by Django 4.2.3 on 2025-07-01 21:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0073_rawtext_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawTextProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(help_text="Which AI model was used, e.g., 'gpt-4o'", max_length=255)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional notes, e.g., error messages or warnings', null=True)),
                ('rawtext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_records', to='narratives.rawtext')),
            ],
        ),
    ]
