# Generated by Django 4.2.28 on 2026-02-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0074_rawtextprocessing'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='rss_url',
            field=models.URLField(blank=True, help_text='Optional RSS feed URL for this source', null=True),
        ),
    ]
