# Generated by Django 4.2.28 on 2026-02-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0075_source_rss_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtext',
            name='is_new',
            field=models.BooleanField(default=True, help_text='Whether this article was just imported'),
        ),
    ]
