# Generated by Django 4.2.28 on 2026-02-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0076_rawtext_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL of the channel/source avatar image', null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the channel/source', null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='external_id',
            field=models.CharField(blank=True, help_text='External ID of the channel/account', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='handle',
            field=models.CharField(blank=True, help_text='Handle of the channel/account, e.g., @vitalik', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='owner_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sources', to='narratives.organization'),
        ),
        migrations.AddField(
            model_name='source',
            name='owner_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sources', to='narratives.person'),
        ),
        migrations.AddField(
            model_name='source',
            name='platform',
            field=models.CharField(choices=[('direct', 'Direct/RSS'), ('youtube', 'YouTube Channel'), ('twitter', 'Twitter/X Account'), ('telegram', 'Telegram Channel')], default='direct', max_length=50),
        ),
        migrations.AddField(
            model_name='source',
            name='subscriber_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of subscribers/followers'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(help_text='The name of the source, e.g., Vitalik Buterin', max_length=255, unique=True),
        ),
    ]
