# Generated by Django 4.2.28 on 2026-02-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0077_source_avatar_url_source_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='narratives.topic'),
        ),
    ]
