# Generated by Django 4.2.28 on 2026-02-26 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0078_source_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtext',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='source',
            name='is_new',
            field=models.BooleanField(default=True, help_text='Whether this source was just added'),
        ),
    ]
