# Generated by Django 4.2.28 on 2026-02-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0079_rawtext_created_at_source_created_at_source_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='avatar_file',
            field=models.ImageField(blank=True, help_text='Uploaded avatar image', null=True, upload_to='sources/avatars/'),
        ),
    ]
