# Generated by Django 4.2.28 on 2026-02-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0080_source_avatar_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtext',
            name='is_updated',
            field=models.BooleanField(default=False, help_text='Whether this article was updated with new info'),
        ),
    ]
