# Generated by Django 4.2.28 on 2026-03-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0081_rawtext_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='sub_topics', to='narratives.topic'),
        ),
    ]
