# Generated by Django 4.2.28 on 2026-03-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0082_topic_description_topic_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='Keywords for LLM/search to identify this topic'),
        ),
    ]
