# Generated by Django 4.2.28 on 2026-03-04 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0083_topic_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(help_text='The sentence or snippet where the topic was found')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rawtext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_topics', to='narratives.rawtext')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_rawtexts', to='narratives.topic')),
            ],
            options={
                'unique_together': {('rawtext', 'topic')},
            },
        ),
    ]
