# Generated by Django 4.2.28 on 2026-03-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0084_pendingtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtopic',
            name='matched_keyword',
            field=models.CharField(blank=True, help_text='The exact keyword that triggered the match', max_length=255, null=True),
        ),
    ]
