# Generated by Django 4.2.28 on 2026-03-05 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0085_pendingtopic_matched_keyword'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendingtopic',
            unique_together=set(),
        ),
    ]
