# Generated by Django 4.2.28 on 2026-03-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0086_alter_pendingtopic_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtext',
            name='categorization_version',
            field=models.CharField(blank=True, help_text='The version of the categorization logic used', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rawtext',
            name='last_categorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
