# Generated by Django 4.2.28 on 2026-03-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0087_rawtext_categorization_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Config key, e.g., 'categorization_version'", max_length=100, unique=True)),
                ('value', models.CharField(help_text='Config value', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
