# Generated by Django 4.2.28 on 2026-03-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0088_appconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtopic',
            name='is_weak',
            field=models.BooleanField(default=False, help_text='Whether this match was from a weak keyword'),
        ),
        migrations.AddField(
            model_name='topic',
            name='weak_keywords',
            field=models.JSONField(blank=True, default=list, help_text="List of dicts: [{'keyword': 'gas', 'required_context': ['blockchain'], 'distance': 10}]"),
        ),
        migrations.AlterField(
            model_name='topic',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='Strong keywords (no AI check needed)'),
        ),
    ]
