# Generated by Django 4.2.28 on 2026-03-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0089_pendingtopic_is_weak_topic_weak_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='claim',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='verification_status',
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
        migrations.DeleteModel(
            name='VerificationStatus',
        ),
    ]
