# Generated by Django 4.2.28 on 2026-03-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0090_remove_market_claim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data for specific types (e.g., bio for persons)'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
