# Generated by Django 4.2.28 on 2026-03-06 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0091_topic_metadata_alter_topic_name_alter_topic_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='owner_organization',
        ),
        migrations.RemoveField(
            model_name='source',
            name='owner_person',
        ),
        migrations.AlterField(
            model_name='rawtext',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_rawtexts', to='narratives.topic'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
