# Generated by Django 4.2.28 on 2026-03-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0092_remove_source_owner_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='related_topics',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='narratives.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='narratives.topic'),
        ),
        migrations.DeleteModel(
            name='SchoolOfThought',
        ),
        migrations.DeleteModel(
            name='SchoolOfThoughtType',
        ),
    ]
