# Generated by Django 4.2.28 on 2026-03-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0093_topic_related_topics_alter_topic_parents_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Value',
        ),
    ]
