# Generated by Django 4.2.28 on 2026-03-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0094_delete_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_placeholder',
            field=models.BooleanField(default=False, help_text='If true, this topic will not be searched in texts (used only for hierarchy)'),
        ),
    ]
