# Generated by Django 4.2.28 on 2026-03-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0095_topic_is_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtopic',
            name='found_context_words',
            field=models.JSONField(blank=True, default=list, help_text='List of context words found near the weak keyword'),
        ),
    ]
