# Generated by Django 4.2.28 on 2026-03-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0096_pendingtopic_found_context_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='alternative_name',
            field=models.CharField(blank=True, help_text='Alternative name for this topic (e.g., Freedom of Expression for Freedom of Speech)', max_length=500, null=True),
        ),
    ]
