# Generated by Django 4.2.28 on 2026-03-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0097_topic_alternative_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='schools_of_thought',
            field=models.ManyToManyField(blank=True, help_text='Schools of thought that this topic belongs to or is defined by', related_name='topics_in_school', to='narratives.topic'),
        ),
    ]
