# Generated by Django 4.2.28 on 2026-03-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0098_topic_schools_of_thought'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
