# Generated by Django 4.2.28 on 2026-03-07 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0099_topic_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_type',
            field=models.ForeignKey(blank=True, help_text='The classification type of this topic (e.g., Person, Crypto, Organization)', limit_choices_to={'is_placeholder': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typed_topics', to='narratives.topic'),
        ),
    ]
