# Generated by Django 4.2.28 on 2026-03-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0100_topic_topic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='functions',
            field=models.ManyToManyField(blank=True, help_text='The primary functions/roles of this topic (e.g., Money -> Medium of Exchange)', related_name='function_of', to='narratives.topic'),
        ),
    ]
