# Generated by Django 4.2.28 on 2026-03-08 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0101_topic_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclinedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The rejected topic name', max_length=500)),
                ('target_field', models.CharField(help_text='Field it was intended for (parents, functions, etc.)', max_length=50)),
                ('reason', models.CharField(choices=[('starts_with_verb', 'Starts with a verb'), ('too_short', 'Too short'), ('complex_phrase', 'Too complex/Not atomic'), ('other', 'Other')], default='other', max_length=50)),
                ('reason_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_suggestions', to='narratives.topic')),
            ],
        ),
    ]
