# Generated by Django 4.2.28 on 2026-03-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0102_declinedtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declinedtopic',
            name='reason',
            field=models.CharField(choices=[('starts_with_verb', 'Starts with a verb'), ('too_short', 'Too short'), ('complex_phrase', 'Too complex/Not atomic'), ('wikipedia_missing', 'Wikipedia page missing'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
