# Generated by Django 4.2.28 on 2026-03-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0103_alter_declinedtopic_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='wikipedia_url',
            field=models.URLField(blank=True, help_text='Direct link to the Wikipedia article (to avoid disambiguation pages)', null=True),
        ),
    ]
