# Generated by Django 4.2.28 on 2026-03-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0104_topic_wikipedia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtext',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=list, help_text='Cached AI topic suggestions for this text'),
        ),
    ]
