# Generated by Django 4.2.28 on 2026-03-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0105_rawtext_ai_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='functions',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='parents',
        ),
    ]
