# Generated by Django 4.2.28 on 2026-03-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0106_remove_topic_functions_remove_topic_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_type',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_type_new',
            field=models.ForeignKey(blank=True, help_text='The classification type of this topic (e.g., Person, Crypto, Organization)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='narratives.topictype'),
        ),
    ]
