# Generated by Django 4.2.28 on 2026-03-08 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0107_topictype_remove_topic_topic_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_type_new',
            new_name='topic_type',
        ),
    ]
