# Generated by Django 4.2.28 on 2026-03-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0108_rename_topic_type_new_topic_topic_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epoch',
            options={'ordering': ['typical_start_date'], 'verbose_name_plural': 'Epochs'},
        ),
        migrations.RemoveField(
            model_name='epoch',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='epoch',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='epoch',
            name='title',
        ),
        migrations.AddField(
            model_name='epoch',
            name='core_end_date',
            field=models.IntegerField(blank=True, help_text="Point after which the epoch's core form begins to dissolve or transform", null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='core_start_date',
            field=models.IntegerField(blank=True, help_text='Point after which the epoch is clearly established or dominant (e.g., 1789 for Modernity)', null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='earliest_start_date',
            field=models.IntegerField(blank=True, help_text='Earliest plausible scholarly start (e.g., 1450 for Modernity)', null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='latest_end_date',
            field=models.IntegerField(blank=True, help_text='Latest plausible scholarly end', null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='name',
            field=models.CharField(blank=True, help_text="Name of the epoch, e.g., 'Modernity', 'The Axial Age'", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='notes_on_periodization',
            field=models.TextField(blank=True, help_text='Explanation of why these specific boundaries were chosen', null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='source_summary',
            field=models.TextField(blank=True, help_text='Summary of scholarly sources used for this periodization', null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='typical_end_date',
            field=models.IntegerField(blank=True, help_text='Commonly used or representative end', null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='typical_start_date',
            field=models.IntegerField(blank=True, help_text='Commonly used or representative start (e.g., 1500 for Modernity)', null=True),
        ),
    ]
