# Generated by Django 4.2.28 on 2026-03-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0109_alter_epoch_options_remove_epoch_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoch',
            name='core_start_date',
            field=models.IntegerField(help_text='Point after which the epoch is clearly established or dominant (e.g., 1789 for Modernity)'),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='earliest_start_date',
            field=models.IntegerField(help_text='Earliest plausible scholarly start (e.g., 1450 for Modernity)'),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='name',
            field=models.CharField(help_text="Name of the epoch, e.g., 'Modernity', 'The Axial Age'", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='typical_start_date',
            field=models.IntegerField(help_text='Commonly used or representative start (e.g., 1500 for Modernity)'),
        ),
    ]
