# Generated by Django 4.2.28 on 2026-03-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0110_alter_epoch_core_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epoch_data', to='narratives.topic'),
        ),
    ]
