# Generated by Django 4.2.28 on 2026-03-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0111_epoch_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtopic',
            name='swot_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Survey-like analysis: {pestel_category, impact_strength (1-4), stance (-2 to +2), summary}'),
        ),
        migrations.AddField(
            model_name='topictype',
            name='is_swot',
            field=models.BooleanField(default=False, help_text='If true, topics of this type will trigger SWOT/PESTEL analysis when found in text'),
        ),
    ]
