# Generated by Django 4.2.28 on 2026-03-09 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0112_pendingtopic_swot_analysis_topictype_is_swot'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictype',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Parent type for hierarchy, e.g. 'Political threat' → parent 'Threat'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='narratives.topictype'),
        ),
        migrations.AlterField(
            model_name='topictype',
            name='is_swot',
            field=models.BooleanField(default=False, help_text='If true, topics of this type (or any descendant) will trigger SWOT/PESTEL analysis when found in text'),
        ),
    ]
