# Generated by Django 4.2.28

from django.db import migrations


def seed_frameworks_and_categories(apps, schema_editor):
    AnalyticalFramework = apps.get_model("narratives", "AnalyticalFramework")
    AnalyticalCategory = apps.get_model("narratives", "AnalyticalCategory")

    swot, _ = AnalyticalFramework.objects.get_or_create(slug="swot", defaults={"name": "SWOT"})
    pestel, _ = AnalyticalFramework.objects.get_or_create(slug="pestel", defaults={"name": "PESTEL"})

    swot_categories = ["Strength", "Weakness", "Opportunity", "Threat"]
    for name in swot_categories:
        slug = name.lower().replace(" ", "-")
        AnalyticalCategory.objects.get_or_create(framework=swot, slug=slug, defaults={"name": name})

    pestel_categories = ["Political", "Economic", "Social", "Technological", "Environmental", "Legal"]
    for name in pestel_categories:
        slug = name.lower()
        AnalyticalCategory.objects.get_or_create(framework=pestel, slug=slug, defaults={"name": name})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("narratives", "0114_analytical_framework_analytical_category_topicanalyticalcategory"),
    ]

    operations = [
        migrations.RunPython(seed_frameworks_and_categories, noop),
    ]
