# Generated by Django 4.2.28

from django.db import migrations


THREAT_TYPE_NAMES = [
    "Threat",
    "Political threat",
    "Economic threat",
    "Social threat",
    "Technological threat",
    "Environmental threat",
    "Legal threat",
]

PESTEL_MAP = {
    "Political threat": "political",
    "Economic threat": "economic",
    "Social threat": "social",
    "Technological threat": "technological",
    "Environmental threat": "environmental",
    "Legal threat": "legal",
}


def migrate_threat_topics_and_delete_types(apps, schema_editor):
    Topic = apps.get_model("narratives", "Topic")
    TopicType = apps.get_model("narratives", "TopicType")
    AnalyticalFramework = apps.get_model("narratives", "AnalyticalFramework")
    AnalyticalCategory = apps.get_model("narratives", "AnalyticalCategory")
    TopicAnalyticalCategory = apps.get_model("narratives", "TopicAnalyticalCategory")

    swot = AnalyticalFramework.objects.filter(slug="swot").first()
    pestel = AnalyticalFramework.objects.filter(slug="pestel").first()
    if not swot or not pestel:
        return

    swot_threat_cat = AnalyticalCategory.objects.filter(framework=swot, slug="threat").first()
    pestel_by_slug = {c.slug: c for c in AnalyticalCategory.objects.filter(framework=pestel)}

    for tt in TopicType.objects.filter(name__in=THREAT_TYPE_NAMES).select_related("parent"):
        topics = Topic.objects.filter(topic_type=tt)
        for topic in topics:
            if swot_threat_cat:
                TopicAnalyticalCategory.objects.get_or_create(
                    topic=topic,
                    analytical_category=swot_threat_cat,
                )
            pestel_slug = PESTEL_MAP.get(tt.name)
            if pestel_slug and pestel_slug in pestel_by_slug:
                TopicAnalyticalCategory.objects.get_or_create(
                    topic=topic,
                    analytical_category=pestel_by_slug[pestel_slug],
                )
            topic.topic_type = None
            topic.save()
        tt.delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("narratives", "0115_seed_analytical_frameworks"),
    ]

    operations = [
        migrations.RunPython(migrate_threat_topics_and_delete_types, noop),
    ]
