# Generated by Django 4.2.28 on 2026-03-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0116_migrate_threat_to_analytical_delete_threat_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticalcategory',
            options={'ordering': ['framework', 'name'], 'verbose_name_plural': 'Analytical categories'},
        ),
        migrations.AlterModelOptions(
            name='topicanalyticalcategory',
            options={'ordering': ['topic', 'analytical_category'], 'verbose_name_plural': 'Topic analytical categories'},
        ),
        migrations.AddField(
            model_name='pendingtopic',
            name='found_in',
            field=models.CharField(blank=True, help_text='Zone: title, subtitle, first_paragraph (lead), content', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='pendingtopic',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, help_text='Importance weight; e.g. 5 for first paragraph (lead) on direct sources'),
        ),
    ]
