# Generated by Django 4.2.28 on 2026-03-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0117_pendingtopic_found_in_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Reference in required_context as [slug], e.g. CRYPTO_WEAK_CONTEXT', max_length=80, unique=True)),
                ('name', models.CharField(blank=True, help_text='Display name', max_length=255)),
                ('words', models.JSONField(default=list, help_text="List of context words, e.g. ['crypto', 'token', 'marketcap']")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
