# Generated by Django 4.2 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("narratives", "0120_enrich_blockchain_network_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawtext",
            name="recently_recategorized_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="Set when this rawtext was in the last 'Re-categorize these articles' batch; cleared on next such run.",
            ),
        ),
    ]
