# Generated by Django 4.2.28 on 2026-03-11 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0121_rawtext_recently_recategorized_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicMentionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Calendar day (from article published_at or rawtext created_at)')),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of approved mentions on this day')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention_days', to='narratives.topic')),
            ],
            options={
                'ordering': ['topic', 'date'],
                'indexes': [models.Index(fields=['topic', 'date'], name='narratives__topic_i_2f7496_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='topicmentionday',
            constraint=models.UniqueConstraint(fields=('topic', 'date'), name='narratives_topicmentionday_topic_date_uniq'),
        ),
    ]
