# Generated by Django 4.2.28 on 2026-03-11 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0122_topicmentionday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declinedtopic',
            name='reason_detail',
            field=models.TextField(blank=True, help_text='Explanation for the decline.', null=True),
        ),
        migrations.AlterField(
            model_name='declinedtopic',
            name='source_topic',
            field=models.ForeignKey(blank=True, help_text='Topic that was being enhanced (null if declined from API or AI suggest).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_suggestions', to='narratives.topic'),
        ),
        migrations.AlterField(
            model_name='declinedtopic',
            name='target_field',
            field=models.CharField(blank=True, help_text='Context: e.g. schools, related, api_create, ai_suggest.', max_length=50),
        ),
    ]
